//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPayment
    {
        public int BillPaymentId { get; set; }
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int ProfessionalId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> BillCreationDate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
        public string CGST { get; set; }
        public string SGST { get; set; }
    }
}
