//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyInfoId { get; set; }
        public string Companyname { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhoneNo1 { get; set; }
        public string CompanyPhoneNo2 { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanySlogan { get; set; }
    }
}
