//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeServicesEntities : DbContext
    {
        public HomeServicesEntities()
            : base("name=HomeServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillPayment> BillPayments { get; set; }
        public virtual DbSet<BillPaymentDetail> BillPaymentDetails { get; set; }
        public virtual DbSet<CardInformation> CardInformations { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerComplaint> CustomerComplaints { get; set; }
        public virtual DbSet<DeviceToken> DeviceTokens { get; set; }
        public virtual DbSet<IsNotificationShown> IsNotificationShowns { get; set; }
        public virtual DbSet<MailCredential> MailCredentials { get; set; }
        public virtual DbSet<OrderRating> OrderRatings { get; set; }
        public virtual DbSet<OrderRequest> OrderRequests { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderWithProfessional> OrderWithProfessionals { get; set; }
        public virtual DbSet<PartnerProfessional> PartnerProfessionals { get; set; }
        public virtual DbSet<PAT_DEMOGRAPHICS> PAT_DEMOGRAPHICS { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Pincode> Pincodes { get; set; }
        public virtual DbSet<PreferOTP> PreferOTPs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ServiceProvided> ServiceProvideds { get; set; }
        public virtual DbSet<SMSApi> SMSApis { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WatsappCredential> WatsappCredentials { get; set; }
    }
}
