//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailCredential
    {
        public int MailCredentialsId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
        public Nullable<int> PortNo { get; set; }
        public Nullable<bool> UseDefaultCredentials { get; set; }
    }
}
