//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRating
    {
        public int OrderRatingId { get; set; }
        public string Ratings { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Usercomments { get; set; }
    }
}
