//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderWithProfessional
    {
        public int OrderProfessionalId { get; set; }
        public int OrderId { get; set; }
        public int ProfessionalId { get; set; }
        public Nullable<System.DateTime> SelectedDateTime { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PartnerProfessional PartnerProfessional { get; set; }
    }
}
