//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.IsNotificationShowns = new HashSet<IsNotificationShown>();
            this.OrderRequests = new HashSet<OrderRequest>();
            this.OrderWithProfessionals = new HashSet<OrderWithProfessional>();
        }
    
        public int OrderId { get; set; }
        public int SubCategoryId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderTime { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string GuestName { get; set; }
        public string GuestPhone { get; set; }
        public string GuestEmail { get; set; }
        public Nullable<int> GuestPincodeId { get; set; }
        public Nullable<int> GuestCityId { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsPaymentDone { get; set; }
        public Nullable<System.DateTime> DeliveredDateTime { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string Rating { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OrderPlacedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsGoingOn { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<System.DateTime> SelectedDate { get; set; }
        public Nullable<int> IsLocked { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsNotificationShown> IsNotificationShowns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Pincode Pincode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderWithProfessional> OrderWithProfessionals { get; set; }
    }
}
