//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAT_DEMOGRAPHICS
    {
        public Nullable<int> BED_NO { get; set; }
        public int MRNO { get; set; }
        public string FIRSTNAME { get; set; }
        public string AGE { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOAH { get; set; }
        public Nullable<System.DateTime> DOAICU { get; set; }
        public string DIAGNOSIS { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> ICUDAY { get; set; }
        public string ENTERED_BY { get; set; }
        public string MOBILE { get; set; }
        public string OUTCOME { get; set; }
        public string PAT_STATUS { get; set; }
    }
}
