//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSApi
    {
        public int SMSApiId { get; set; }
        public string SMSUrl { get; set; }
        public string SMSApiKey { get; set; }
        public string Sender { get; set; }
    }
}
